"""
NSE Top 500 Tickers + Sector Mapping (v2 - Yahoo-verified symbols)
Used by stock_scanner.py for universe scanning and sector rotation

v2 Changes: Fixed 27 ticker symbols that failed on Yahoo Finance
"""

# ============================================================
# NSE 500 — Organized by Sector (Yahoo Finance verified)
# ============================================================

NSE_BY_SECTOR = {
    'BANKING': {
        'HDFCBANK': 'HDFC Bank',
        'ICICIBANK': 'ICICI Bank',
        'SBIN': 'State Bank of India',
        'KOTAKBANK': 'Kotak Mahindra Bank',
        'AXISBANK': 'Axis Bank',
        'INDUSINDBK': 'IndusInd Bank',
        'PNB': 'Punjab National Bank',
        'BANKBARODA': 'Bank of Baroda',
        'CANBK': 'Canara Bank',
        'UNIONBANK': 'Union Bank',
        'IDFCFIRSTB': 'IDFC First Bank',
        'BANDHANBNK': 'Bandhan Bank',
        'FEDERALBNK': 'Federal Bank',
        'YESBANK': 'Yes Bank',
        'AUBANK': 'AU Small Finance Bank',
        'IDBI': 'IDBI Bank',
        'IOB': 'Indian Overseas Bank',
        'INDIANB': 'Indian Bank',
        'CUB': 'City Union Bank',
        'KARURVYSYA': 'Karur Vysya Bank',
        'RBLBANK': 'RBL Bank',
        'CSBBANK': 'CSB Bank',
        'DCBBANK': 'DCB Bank',
        'SOUTHBANK': 'South Indian Bank',
        'UCOBANK': 'UCO Bank',
        'CENTRALBK': 'Central Bank of India',
        'MAHABANK': 'Bank of Maharashtra',
        'J&KBANK': 'J&K Bank',
        'EQUITASBNK': 'Equitas Small Finance',
        'UJJIVANSFB': 'Ujjivan Small Finance',
    },
    'NBFC_FINANCE': {
        'BAJFINANCE': 'Bajaj Finance',
        'BAJAJFINSV': 'Bajaj Finserv',
        'CHOLAFIN': 'Cholamandalam Finance',
        'SHRIRAMFIN': 'Shriram Finance',
        'M&MFIN': 'M&M Financial',
        'MUTHOOTFIN': 'Muthoot Finance',
        'MANAPPURAM': 'Manappuram Finance',
        'PFC': 'Power Finance Corp',
        'RECLTD': 'REC Limited',
        'IRFC': 'Indian Railway Finance',
        'LICHSGFIN': 'LIC Housing Finance',
        'HDFCAMC': 'HDFC AMC',
        'HDFCLIFE': 'HDFC Life Insurance',
        'SBILIFE': 'SBI Life Insurance',
        'ICICIPRULI': 'ICICI Prudential Life',
        'ICICIGI': 'ICICI Lombard',
        'LICI': 'Life Insurance Corp',
        'SBICARD': 'SBI Cards',
        'POLICYBZR': 'PB Fintech',
        'PAYTM': 'One97 Communications',
        'JIOFIN': 'Jio Financial Services',
        'IIFL': 'IIFL Finance',
        'NAM-INDIA': 'Nippon Life AMC',
        'CDSL': 'Central Depository Services',
        'BSE': 'BSE Ltd',
        'MCX': 'Multi Commodity Exchange',
        'IEX': 'Indian Energy Exchange',
        'CAMS': 'CAMS',
        'KFINTECH': 'KFin Technologies',
        'ABCAPITAL': 'Aditya Birla Capital',
        'CREDITACC': 'CreditAccess Grameen',
        'MASFIN': 'MAS Financial',
        'POONAWALLA': 'Poonawalla Fincorp',
        'STARHEALTH': 'Star Health Insurance',
        'GICRE': 'GIC Re',
        'UTIAMC': 'UTI AMC',
    },
    'IT': {
        'TCS': 'Tata Consultancy Services',
        'INFY': 'Infosys',
        'WIPRO': 'Wipro',
        'HCLTECH': 'HCL Technologies',
        'TECHM': 'Tech Mahindra',
        'LTIM': 'LTIMindtree',
        'PERSISTENT': 'Persistent Systems',
        'COFORGE': 'Coforge',
        'MPHASIS': 'Mphasis',
        'OFSS': 'Oracle Financial Services',
        'KPITTECH': 'KPIT Technologies',
        'TATAELXSI': 'Tata Elxsi',
        'LTTS': 'L&T Technology Services',
        'ZENSARTECH': 'Zensar Technologies',
        'BSOFT': 'Birlasoft',
        'CYIENT': 'Cyient',
        'INTELLECT': 'Intellect Design',
        'HAPPSTMNDS': 'Happiest Minds',
        'NEWGEN': 'Newgen Software',
        'ROUTE': 'Route Mobile',
        'SONATSOFTW': 'Sonata Software',
        'ECLERX': 'eClerx Services',
        'MASTEK': 'Mastek',
    },
    'ENERGY_OIL': {
        'RELIANCE': 'Reliance Industries',
        'ONGC': 'Oil & Natural Gas Corp',
        'IOC': 'Indian Oil Corp',
        'BPCL': 'Bharat Petroleum',
        'HINDPETRO': 'Hindustan Petroleum',
        'GAIL': 'GAIL India',
        'OIL': 'Oil India',
        'PETRONET': 'Petronet LNG',
        'IGL': 'Indraprastha Gas',
        'MGL': 'Mahanagar Gas',
        'GUJGASLTD': 'Gujarat Gas',
        'CASTROLIND': 'Castrol India',
        'GSPL': 'Gujarat State Petronet',
        'AEGISLOG': 'Aegis Logistics',
    },
    'POWER': {
        'NTPC': 'NTPC',
        'POWERGRID': 'Power Grid Corp',
        'TATAPOWER': 'Tata Power',
        'ADANIPOWER': 'Adani Power',
        'ADANIGREEN': 'Adani Green Energy',
        'ADANIENSOL': 'Adani Energy Solutions',
        'JSWENERGY': 'JSW Energy',
        'NHPC': 'NHPC',
        'SJVN': 'SJVN',
        'TORNTPOWER': 'Torrent Power',
        'CESC': 'CESC',
        'SUZLON': 'Suzlon Energy',
        'INOXWIND': 'Inox Wind',
        'NLCINDIA': 'NLC India',
        'KEC': 'KEC International',
        'PTC': 'PTC India',
        'JPPOWER': 'Jaiprakash Power',
    },
    'AUTO': {
        'TATAMOTORS': 'Tata Motors',
        'M&M': 'Mahindra & Mahindra',
        'MARUTI': 'Maruti Suzuki',
        'BAJAJ-AUTO': 'Bajaj Auto',
        'EICHERMOT': 'Eicher Motors',
        'HEROMOTOCO': 'Hero MotoCorp',
        'TVSMOTOR': 'TVS Motor',
        'ASHOKLEY': 'Ashok Leyland',
        'BHARATFORG': 'Bharat Forge',
        'BOSCHLTD': 'Bosch',
        'MOTHERSON': 'Samvardhana Motherson',
        'BALKRISIND': 'Balkrishna Industries',
        'MRF': 'MRF',
        'APOLLOTYRE': 'Apollo Tyres',
        'CEATLTD': 'CEAT',
        'EXIDEIND': 'Exide Industries',
        'ESCORTS': 'Escorts Kubota',
        'ARE&M': 'Amara Raja Energy',
        'SUNDRMFAST': 'Sundram Fasteners',
        'ENDURANCE': 'Endurance Technologies',
        'JKTYRE': 'JK Tyre',
        'UNOMINDA': 'UNO Minda',
        'TIINDIA': 'Tube Investments',
        'WABAG': 'VA Tech Wabag',
        'ZFCVINDIA': 'ZF Commercial',
    },
    'PHARMA': {
        'SUNPHARMA': 'Sun Pharma',
        'DRREDDY': "Dr Reddy's Labs",
        'CIPLA': 'Cipla',
        'DIVISLAB': "Divi's Labs",
        'LUPIN': 'Lupin',
        'AUROPHARMA': 'Aurobindo Pharma',
        'BIOCON': 'Biocon',
        'TORNTPHARM': 'Torrent Pharma',
        'ALKEM': 'Alkem Labs',
        'ZYDUSLIFE': 'Zydus Lifesciences',
        'GLENMARK': 'Glenmark Pharma',
        'IPCALAB': 'Ipca Labs',
        'LAURUSLABS': 'Laurus Labs',
        'NATCOPHARM': 'Natco Pharma',
        'GLAND': 'Gland Pharma',
        'ABBOTINDIA': 'Abbott India',
        'PFIZER': 'Pfizer',
        'GLAXO': 'GSK Pharma',
        'SANOFI': 'Sanofi India',
        'AJANTPHARM': 'Ajanta Pharma',
        'JBCHEPHARM': 'JB Chemicals',
        'GRANULES': 'Granules India',
        'PPLPHARMA': 'Piramal Pharma',
        'STAR': 'Strides Pharma',
        'WOCKPHARMA': 'Wockhardt',
        'CAPLIPOINT': 'Caplin Point',
        'ERIS': 'Eris Lifesciences',
        'FDC': 'FDC',
        'INDOCO': 'Indoco Remedies',
    },
    'HEALTHCARE': {
        'APOLLOHOSP': 'Apollo Hospitals',
        'MAXHEALTH': 'Max Healthcare',
        'FORTIS': 'Fortis Healthcare',
        'METROPOLIS': 'Metropolis Healthcare',
        'LALPATHLAB': 'Dr Lal PathLabs',
        'SYNGENE': 'Syngene International',
        'KIMS': 'Krishna Institute',
        'NH': 'Narayana Hrudayalaya',
        'GLOBAL': 'Global Health (Medanta)',
        'HCG': 'HealthCare Global',
        'POLYMED': 'Poly Medicure',
        'KRSNAA': 'Krsnaa Diagnostics',
    },
    'FMCG': {
        'HINDUNILVR': 'Hindustan Unilever',
        'ITC': 'ITC',
        'NESTLEIND': 'Nestle India',
        'BRITANNIA': 'Britannia Industries',
        'DABUR': 'Dabur India',
        'GODREJCP': 'Godrej Consumer',
        'MARICO': 'Marico',
        'COLPAL': 'Colgate-Palmolive',
        'TATACONSUM': 'Tata Consumer Products',
        'EMAMILTD': 'Emami',
        'UBL': 'United Breweries',
        'RADICO': 'Radico Khaitan',
        'VBL': 'Varun Beverages',
        'UNITDSPR': 'United Spirits',
        'PATANJALI': 'Patanjali Foods',
        'GODFRYPHLP': 'Godfrey Phillips',
        'VSTIND': 'VST Industries',
        'JYOTHYLAB': 'Jyothy Labs',
        'BAJAJCON': 'Bajaj Consumer',
        'GILLETTE': 'Gillette India',
        'PGHH': 'P&G Hygiene',
        'HONASA': 'Honasa Consumer (Mamaearth)',
    },
    'METALS_MINING': {
        'TATASTEEL': 'Tata Steel',
        'JSWSTEEL': 'JSW Steel',
        'HINDALCO': 'Hindalco',
        'VEDL': 'Vedanta',
        'JINDALSTEL': 'Jindal Steel',
        'SAIL': 'SAIL',
        'NMDC': 'NMDC',
        'NATIONALUM': 'National Aluminium',
        'COALINDIA': 'Coal India',
        'HINDZINC': 'Hindustan Zinc',
        'APLAPOLLO': 'APL Apollo Tubes',
        'JINDALSAW': 'Jindal Saw',
        'WELCORP': 'Welspun Corp',
        'MOIL': 'MOIL',
        'GMDCLTD': 'Gujarat Mineral',
        'RATNAMANI': 'Ratnamani Metals',
        'JSL': 'Jindal Stainless',
        'ELECON': 'Elecon Engineering',
    },
    'CEMENT': {
        'ULTRACEMCO': 'UltraTech Cement',
        'SHREECEM': 'Shree Cement',
        'AMBUJACEM': 'Ambuja Cements',
        'ACC': 'ACC',
        'DALBHARAT': 'Dalmia Bharat',
        'JKCEMENT': 'JK Cement',
        'RAMCOCEM': 'Ramco Cements',
        'HEIDELBERG': 'Heidelberg Cement',
        'STARCEMENT': 'Star Cement',
        'INDIACEM': 'India Cements',
        'PRISMCEM': 'Prism Johnson',
        'BIRLACORPN': 'Birla Corporation',
    },
    'TELECOM': {
        'BHARTIARTL': 'Bharti Airtel',
        'IDEA': 'Vodafone Idea',
        'TATACOMM': 'Tata Communications',
        'INDUSTOWER': 'Indus Towers',
        'HFCL': 'HFCL',
        'ROUTE': 'Route Mobile',
        'STLTECH': 'Sterlite Technologies',
    },
    'CONSUMER_DURABLES': {
        'TITAN': 'Titan Company',
        'ASIANPAINT': 'Asian Paints',
        'BERGEPAINT': 'Berger Paints',
        'PIDILITIND': 'Pidilite Industries',
        'KAJARIACER': 'Kajaria Ceramics',
        'CROMPTON': 'Crompton Greaves',
        'HAVELLS': 'Havells India',
        'VOLTAS': 'Voltas',
        'BLUESTARCO': 'Blue Star',
        'WHIRLPOOL': 'Whirlpool India',
        'DIXON': 'Dixon Technologies',
        'AMBER': 'Amber Enterprises',
        'POLYCAB': 'Polycab India',
        'KEI': 'KEI Industries',
        'FINPIPE': 'Finolex Industries',
        'BAJAJELEC': 'Bajaj Electricals',
        'ORIENTELEC': 'Orient Electric',
        'VGUARD': 'V-Guard Industries',
        'SYMPHONY': 'Symphony',
        'RELAXO': 'Relaxo Footwears',
        'BATAINDIA': 'Bata India',
        'TTKPRESTIG': 'TTK Prestige',
        'CERA': 'Cera Sanitaryware',
        'SFL': 'Sheela Foam',
        'GREENLAM': 'Greenlam Industries',
        'CENTURYPLY': 'Century Plyboards',
        'STYLAMIND': 'Stylam Industries',
        'GREENPLY': 'Greenply Industries',
        'NILKAMAL': 'Nilkamal',
        'BORORENEW': 'Borosil Renewables',
        'IFBIND': 'IFB Industries',
    },
    'RETAIL': {
        'DMART': 'Avenue Supermarts',
        'TRENT': 'Trent',
        'NYKAA': 'FSN E-Commerce (Nykaa)',
        'ETERNAL': 'Eternal Ltd (Zomato)',
        'ABFRL': 'Aditya Birla Fashion',
        'SHOPERSTOP': 'Shoppers Stop',
        'VMART': 'V-Mart Retail',
        'JUBLFOOD': 'Jubilant FoodWorks',
        'WESTLIFE': 'Westlife Foodworld',
        'DEVYANI': 'Devyani International',
        'SAPPHIRE': 'Sapphire Foods',
        'RBA': 'Restaurant Brands Asia',
        'ARVINDFASN': 'Arvind Fashions',
        'RAYMOND': 'Raymond',
        'V2RETAIL': 'V2 Retail',
    },
    'INFRA_CAPGOODS': {
        'LT': 'Larsen & Toubro',
        'BEL': 'Bharat Electronics',
        'HAL': 'Hindustan Aeronautics',
        'BHEL': 'BHEL',
        'MAZDOCK': 'Mazagon Dock Shipbuilders',
        'COCHINSHIP': 'Cochin Shipyard',
        'GRSE': 'Garden Reach Shipbuilders',
        'BEML': 'BEML',
        'ABB': 'ABB India',
        'SIEMENS': 'Siemens',
        'CUMMINSIND': 'Cummins India',
        'THERMAX': 'Thermax',
        'KPIL': 'Kalpataru Projects',
        'HONAUT': 'Honeywell Automation',
        'AIAENG': 'AIA Engineering',
        'TIMKEN': 'Timken India',
        'SKFINDIA': 'SKF India',
        'GRINDWELL': 'Grindwell Norton',
        'LMW': 'Lakshmi Machine Works',
        'SCHAEFFLER': 'Schaeffler India',
        'TRITURBINE': 'Triveni Turbine',
        'BDL': 'Bharat Dynamics',
        'IDEAFORGE': 'IdeaForge Technology',
        'PARAS': 'Paras Defence',
        'DATAPATTNS': 'Data Patterns',
        'ZENTEC': 'Zen Technologies',
        'ASTRAL': 'Astral Pipes',
        'SUPREMEIND': 'Supreme Industries',
        'KIRLOSBROS': 'Kirloskar Brothers',
        'KIRLOSENG': 'Kirloskar Oil Engines',
        'ISGEC': 'ISGEC Heavy Engineering',
        'PRAJIND': 'Praj Industries',
        'ENGINERSIN': 'Engineers India',
        'AZAD': 'Azad Engineering',
    },
    'CONSTRUCTION_REALTY': {
        'DLF': 'DLF',
        'GODREJPROP': 'Godrej Properties',
        'OBEROIRLTY': 'Oberoi Realty',
        'PRESTIGE': 'Prestige Estates',
        'BRIGADE': 'Brigade Enterprises',
        'PHOENIXLTD': 'Phoenix Mills',
        'LODHA': 'Macrotech Developers',
        'SOBHA': 'Sobha',
        'NCC': 'NCC',
        'IRB': 'IRB Infrastructure',
        'GMRAIRPORT': 'GMR Airports',
        'ADANIPORTS': 'Adani Ports',
        'MAHLIFE': 'Mahindra Lifespace',
        'SUNTECK': 'Sunteck Realty',
        'PURVA': 'Puravankara',
        'ANANTRAJ': 'Anant Raj',
        'KOLTEPATIL': 'Kolte-Patil Developers',
        'ARVSMART': 'Arvind SmartSpaces',
        'HGINFRA': 'HG Infra Engineering',
        'PNCINFRA': 'PNC Infratech',
        'KNRCON': 'KNR Constructions',
        'ASHOKA': 'Ashoka Buildcon',
        'RVNL': 'Rail Vikas Nigam',
        'JWL': 'Jupiter Wagons',
    },
    'CHEMICALS': {
        'UPL': 'UPL',
        'SRF': 'SRF',
        'PIIND': 'PI Industries',
        'AARTIIND': 'Aarti Industries',
        'NAVINFLUOR': 'Navin Fluorine',
        'DEEPAKNTR': 'Deepak Nitrite',
        'TATACHEM': 'Tata Chemicals',
        'ATUL': 'Atul',
        'CLEAN': 'Clean Science',
        'GNFC': 'GNFC',
        'CHAMBLFERT': 'Chambal Fertilisers',
        'COROMANDEL': 'Coromandel International',
        'GSFC': 'GSFC',
        'BASF': 'BASF India',
        'SOLARINDS': 'Solar Industries',
        'FLUOROCHEM': 'Gujarat Fluorochemicals',
        'SUMICHEM': 'Sumitomo Chemical',
        'BAYERCROP': 'Bayer CropScience',
        'RALLIS': 'Rallis India',
        'INSECTICID': 'Insecticides India',
        'ROSSARI': 'Rossari Biotech',
        'NOCIL': 'NOCIL',
        'GHCL': 'GHCL',
        'EIDPARRY': 'EID Parry',
        'BALAMINES': 'Balaji Amines',
        'GALAXYSURF': 'Galaxy Surfactants',
        'SUDARSCHEM': 'Sudarshan Chemical',
        'TANLA': 'Tanla Platforms',
        'EPL': 'EPL',
        'ANDHRSUGAR': 'Andhra Sugars',
    },
    'ADANI_GROUP': {
        'ADANIENT': 'Adani Enterprises',
        'ADANIPORTS': 'Adani Ports',
        'ADANIPOWER': 'Adani Power',
        'ADANIGREEN': 'Adani Green Energy',
        'ADANIENSOL': 'Adani Energy Solutions',
        'ATGL': 'Adani Total Gas',
        'AWL': 'Adani Wilmar',
        'NDTV': 'NDTV',
        'ACC': 'ACC (Adani-controlled)',
        'AMBUJACEM': 'Ambuja (Adani-controlled)',
    },
    'RAILWAYS_DEFENCE': {
        'IRCTC': 'IRCTC',
        'IRFC': 'Indian Railway Finance',
        'RAILTEL': 'RailTel',
        'IRCON': 'Ircon International',
        'RVNL': 'Rail Vikas Nigam',
        'RITES': 'RITES',
        'CONCOR': 'Container Corp',
        'TITAGARH': 'Titagarh Rail Systems',
        'JWL': 'Jupiter Wagons',
        'TEXRAIL': 'Texmaco Rail',
        'BDL': 'Bharat Dynamics',
        'DATAPATTNS': 'Data Patterns',
        'ZENTEC': 'Zen Technologies',
        'PARAS': 'Paras Defence',
        'IDEAFORGE': 'IdeaForge Technology',
    },
    'MEDIA_ENTERTAINMENT': {
        'ZEEL': 'Zee Entertainment',
        'SUNTV': 'Sun TV Network',
        'PVRINOX': 'PVR Inox',
        'NETWORK18': 'Network18 Media',
        'NAZARA': 'Nazara Technologies',
        'SAREGAMA': 'Saregama India',
        'TIPSMUSIC': 'Tips Music',
        'INOXWIND': 'Inox Wind',
        'JAGRAN': 'Jagran Prakashan',
        'DBCORP': 'DB Corp',
        'HTMEDIA': 'HT Media',
    },
    'TEXTILES': {
        'PAGEIND': 'Page Industries',
        'TRIDENT': 'Trident',
        'WELSPUNLIV': 'Welspun Living',
        'VARDHACRLC': 'Vardhman Textiles',
        'KPRMILL': 'KPR Mill',
        'SIYSIL': 'Siyaram Silk Mills',
        'SUTLEJTEX': 'Sutlej Textiles',
        'GOKEX': 'Gokaldas Exports',
        'INDORAMA': 'Indo Rama Synthetics',
        'NITINSPIN': 'Nitin Spinners',
        'GRWRHITECH': 'Garware Hi-Tech',
        'RAYMOND': 'Raymond',
    },
    'AGRI_FOOD': {
        'KSCL': 'Kaveri Seed',
        'GODREJAGRO': 'Godrej Agrovet',
        'BAYERCROP': 'Bayer CropScience',
        'SUMICHEM': 'Sumitomo Chemical',
        'INSECTICID': 'Insecticides India',
        'AVANTIFEED': 'Avanti Feeds',
        'VENKEYS': "Venky's India",
        'GODREJIND': 'Godrej Industries',
        'BALRAMCHIN': 'Balrampur Chini',
        'TRIVENI': 'Triveni Engineering',
        'DHAMPURSUG': 'Dhampur Sugar',
        'EIDPARRY': 'EID Parry',
        'BANARISUG': 'Bannari Amman Sugars',
    },
    'LOGISTICS': {
        'DELHIVERY': 'Delhivery',
        'BLUEDART': 'Blue Dart Express',
        'TCI': 'Transport Corp of India',
        'MAHLOG': 'Mahindra Logistics',
        'GATEWAY': 'Gateway Distriparks',
        'CONCOR': 'Container Corp',
        'ALLCARGO': 'Allcargo Logistics',
        'VRLLOG': 'VRL Logistics',
        'TCIEXP': 'TCI Express',
        'SNOWMAN': 'Snowman Logistics',
    },
    'HOTELS_TRAVEL': {
        'INDIGO': 'InterGlobe Aviation',
        'INDHOTEL': 'Indian Hotels (Taj)',
        'EIHOTEL': 'EIH (Oberoi)',
        'CHALET': 'Chalet Hotels',
        'LEMONTREE': 'Lemon Tree Hotels',
        'MHRIL': 'Mahindra Holidays',
        'EASEMYTRIP': 'EaseMyTrip',
        'TBOTEK': 'TBO Tek',
        'IRCTC': 'IRCTC',
        'TAJGVK': 'Taj GVK Hotels',
    },
    'NEW_AGE_TECH': {
        'PAYTM': 'One97 Communications',
        'NYKAA': 'FSN E-Commerce',
        'POLICYBZR': 'PB Fintech',
        'ETERNAL': 'Eternal (Zomato)',
        'DELHIVERY': 'Delhivery',
        'NAZARA': 'Nazara Technologies',
        'EASEMYTRIP': 'EaseMyTrip',
        'IXIGO': 'Le Travenues (ixigo)',
        'TBOTEK': 'TBO Tek',
        'HONASA': 'Honasa Consumer',
        'CARTRADE': 'CarTrade Tech',
        'RATEGAIN': 'RateGain Travel',
        'TRACXN': 'Tracxn Technologies',
        'MAPMYINDIA': 'CE Info Systems',
        'IKIO': 'IKIO Lighting',
    },
}


def get_all_tickers():
    """Return flat list of all tickers across sectors (deduplicated)"""
    tickers = []
    seen = set()
    for sector, stocks in NSE_BY_SECTOR.items():
        for ticker in stocks.keys():
            if ticker not in seen:
                seen.add(ticker)
                tickers.append(ticker)
    return tickers


def get_ticker_to_sector_map():
    """Reverse map: ticker -> primary sector (first sector wins for duplicates)"""
    mapping = {}
    for sector, stocks in NSE_BY_SECTOR.items():
        for ticker in stocks.keys():
            if ticker not in mapping:
                mapping[ticker] = sector
    return mapping


def get_sector_tickers(sector_name):
    """Get all tickers in a specific sector"""
    return list(NSE_BY_SECTOR.get(sector_name, {}).keys())


def get_yahoo_symbols():
    """Return tickers with .NS suffix for Yahoo Finance"""
    return [f"{t}.NS" for t in get_all_tickers()]


def get_total_count():
    """Total unique tickers"""
    return len(get_all_tickers())


# ============================================================
# QUICK TEST
# ============================================================

if __name__ == "__main__":
    total = get_total_count()
    print(f"Total unique tickers: {total}")
    print(f"\nSectors ({len(NSE_BY_SECTOR)}):")
    for sector, stocks in NSE_BY_SECTOR.items():
        print(f"  {sector}: {len(stocks)} stocks")
    
    print(f"\nFirst 10 tickers: {get_all_tickers()[:10]}")
    print(f"\nYahoo symbol format: {get_yahoo_symbols()[:5]}")
    print(f"\nTicker -> Sector example:")
    sector_map = get_ticker_to_sector_map()
    for t in ['RELIANCE', 'TCS', 'TATAPOWER', 'IRCTC', 'ETERNAL', 'GMRAIRPORT', 'MAPMYINDIA']:
        print(f"  {t}: {sector_map.get(t, 'UNKNOWN')}")